# -*- coding: utf-8 -*-
"""sharpening.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yo6sgnmXnV6V97iiPMQu8NmxX3sq9IzT
"""

import cv2 
import numpy as np 
from google.colab.patches import cv2_imshow
from scipy.ndimage.filters import median_filter

img = cv2.imread("간판_가로형간판_000002_0.jpg") 
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


blurring_mask1 = np.array([[1 / 9, 1 / 9, 1 / 9], 
                           [1 / 9, 1 / 9, 1 / 9], 
                           [1 / 9, 1 / 9, 1 / 9]]) 

blurring_mask2 = np.array([[1 / 25, 1 / 25, 1 / 25, 1 / 25, 1 / 25], 
                           [1 / 25, 1 / 25, 1 / 25, 1 / 25, 1 / 25],
                           [1 / 25, 1 / 25, 1 / 25, 1 / 25, 1 / 25], 
                           [1 / 25, 1 / 25, 1 / 25, 1 / 25, 1 / 25], 
                           [1 / 25, 1 / 25, 1 / 25, 1 / 25, 1 / 25]]) 

smoothing_mask = np.array([[1 / 16, 1 / 8, 1 / 16],
                           [1 / 8, 1 / 4, 1 / 8], 
                           [1 / 16, 1 / 8, 1 / 16]]) 

sharpening_mask1 = np.array([[-1, -1, -1], 
                             [-1, 9, -1], 
                             [-1, -1, -1]]) 

sharpening_mask2 = np.array([[0, -1, 0], 
                             [-1, 5, -1], 
                             [0, -1, 0]]) 
 
##unsharp masking
def unsharp(image,sigma,strength):

  image_mf=median_filter(image,sigma)

  lap=cv2.Laplacian(image_mf,cv2.CV_64F)

  sharp=image-strength*lap

  sharp[sharp>255]=255
  sharp[sharp<0]=0

  return sharp


blurring_out1 = cv2.filter2D(gray, -1, blurring_mask1) 
blurring_out2 = cv2.filter2D(gray, -1, blurring_mask2) 
smoothing_out = cv2.filter2D(gray, -1, smoothing_mask) 
sharpening_out1 = cv2.filter2D(gray, -1, sharpening_mask1) 
sharpening_out2 = cv2.filter2D(gray, -1, sharpening_mask2) 
unsharp_out=unsharp(gray,5,0.8)
 





cv2_imshow(gray) 
cv2_imshow( blurring_out1) 
cv2_imshow( blurring_out2) 
cv2_imshow( smoothing_out) 
cv2_imshow( sharpening_out1) 
cv2_imshow( sharpening_out2) 
cv2_imshow(unsharp_out)


cv2.waitKey(0)